#!/usr/bin/env bash

is_running() {
    test $(systemctl --user is-active redshift) = "active"
}

toggle_mode() {
    if is_running ; then
        systemctl --user stop redshift
    else
        systemctl --user start redshift
    fi
}

print_icon() {
    if [[ $? -eq 0 ]]; then
        temp=$(redshift -p 2>/dev/null | grep temp | cut -d' ' -f3)
        temp=${temp%"K"}
    fi

    icon=""
    if [[ -z $temp ]]; then
        echo "%{F#5A666B}$icon"       # Greyed out (not running)
    elif [[ $temp -ge 5000 ]]; then
        echo "%{F#6998B3}$icon"       # Blue
    elif [[ $temp -ge 4000 ]]; then
        echo "%{F#9B9257}$icon"       # Yellow
    else
        echo "%{F#948556}$icon"       # Orange
    fi
}


case $1 in
    toggle)
        toggle_mode ;;
    print)
        print_icon ;;
esac
